"""
Django settings for DjangoTraders project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-6d_#ekptae2f7tcjel+%(it8p(-*xpq2p^wtvpz92^d=h76c(9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Ships the intcomma template filter (thousands-separator formatting,
    # e.g. 1234.5 -> "1,234.50") used for every currency value across
    # djtraders' templates -- see those templates' own comments for
    # where it's loaded and applied.
    'django.contrib.humanize',
    'djtraders',
    # django-crispy-forms + its Bootstrap 5 template pack -- together
    # they render a Django form as styled Bootstrap 5 markup from a
    # single {% crispy form %} tag. They only change how a form
    # renders, never what it validates (see CRISPY_* settings below).
    'crispy_forms',
    'crispy_bootstrap5',
]

# Required by crispy_forms/crispy_bootstrap5 above -- tells crispy which
# template pack(s) are allowed and which one to use by default.
# settings.py — one-time setup

CRISPY_ALLOWED_TEMPLATE_PACKS = 'bootstrap5'
CRISPY_TEMPLATE_PACK = 'bootstrap5'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'DjangoTraders.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # DIRS lists template folders that live outside any single app --
        # used here for project-level pages (like the site home page)
        # that don't belong to djtraders or any other specific app.
        # APP_DIRS=True (below) is what makes each app's own
        # templates/ folder (e.g. djtraders/templates/) get found too;
        # DIRS and APP_DIRS work together, not as alternatives.
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # Injects current_employee/current_customer into every
                # template's context from request.session -- without
                # this, those variables are always undefined/None, and
                # every {% if current_employee %}-gated block (Edit
                # buttons, Actions columns, etc.) across the site stays
                # hidden even when someone is logged in.
                'djtraders.session_context.current_customer',
                'djtraders.session_context.current_employee',
                'djtraders.session_context.cart_summary',
                'djtraders.session_context.current_supplier',
            ],
        },
    },
]

WSGI_APPLICATION = 'DjangoTraders.wsgi.application'


# Database:
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "DjangoTraders",
        "USER": "postgres",
        "PASSWORD": "1234567890",
        "HOST": "localhost",
        "PORT": "5432",
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
# region [CONCEPT]